# Generated by Django 3.2.9 on 2021-11-05 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_count', models.IntegerField(blank=True, default=1, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('yellow_team', models.CharField(choices=[('win', 'win'), ('loss', 'loss'), ('draw', 'draw')], max_length=64, null=True)),
                ('red_team', models.CharField(choices=[('win', 'win'), ('loss', 'loss'), ('draw', 'draw')], max_length=64, null=True)),
                ('week_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.week')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Attendence_option', models.CharField(choices=[('Jooga', 'Jooga'), ('Maqan', 'Maqan')], max_length=64, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('week_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.week')),
            ],
        ),
    ]
